In [1]:
import os
import pandas as pd

In [11]:
cwd = os.getcwd().split('amts')[0] + 'amts'
theme = "machine_learning"
pd.set_option('display.max_rows', 1000)

In [12]:
input_folder_path = rf"{cwd}/{theme}/data/inputs/CR_training_data"

In [13]:
input_file_path = rf"{input_folder_path}/loan_data_2007_2014.csv"
print(rf"Input File (Raw Data): {input_file_path}")
raw_input_df = pd.read_csv(input_file_path)

Input File (Raw Data): c:\dev\amts/machine_learning/data/inputs/CR_training_data/loan_data_2007_2014.csv

C:\Users\FU689FU\AppData\Local\Temp\ipykernel_51720\2719992523.py:3: DtypeWarning: Columns (20) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_input_df = pd.read_csv(input_file_path)

In [14]:
# Always make a copy of the raw input data so that you don't overwrite the original data
prepped_input_df = raw_input_df.copy()
raw_input_df.head()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,...,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
print(raw_input_df.size)

34971375

In [10]:
describe_df = raw_input_df.describe()
pivoted_descibed_data = pd.pivot_table(describe_df.reset_index(), columns='index')
pivoted_descibed_data

index,25%,50%,75%,count,max,mean,min,std
Unnamed: 0,1.165710e+05,2.331420e+05,3.497130e+05,466285.0,4.662840e+05,2.331420e+05,0.00,1.346050e+05
acc_now_delinq,0.000000e+00,0.000000e+00,0.000000e+00,466256.0,5.000000e+00,4.002093e-03,0.00,6.863680e-02
all_util,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
annual_inc,4.500000e+04,6.300000e+04,8.896000e+04,466281.0,7.500000e+06,7.327738e+04,1896.00,5.496357e+04
annual_inc_joint,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
collection_recovery_fee,0.000000e+00,0.000000e+00,0.000000e+00,466285.0,7.002190e+03,8.961534e+00,0.00,8.549144e+01
collections_12_mths_ex_med,0.000000e+00,0.000000e+00,0.000000e+00,466140.0,2.000000e+01,9.085253e-03,0.00,1.086484e-01
delinq_2yrs,0.000000e+00,0.000000e+00,0.000000e+00,466256.0,2.900000e+01,2.846784e-01,0.00,7.973651e-01
dti,1.136000e+01,1.687000e+01,2.278000e+01,466285.0,3.999000e+01,1.721876e+01,0.00,7.851121e+00
dti_joint,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
funded_amnt,8.000000e+03,1.200000e+04,2.000000e+04,466285.0,3.500000e+04,1.429180e+04,500.00,8.274371e+03
funded_amnt_inv,8.000000e+03,1.200000e+04,1.995000e+04,466285.0,3.500000e+04,1.422233e+04,0.00,8.297638e+03
id,3.639987e+06,1.010790e+07,2.073121e+07,466285.0,3.809811e+07,1.307973e+07,54734.00,1.089371e+07
il_util,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
inq_fi,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
inq_last_12m,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
inq_last_6mths,0.000000e+00,0.000000e+00,1.000000e+00,466256.0,3.300000e+01,8.047446e-01,0.00,1.091598e+00
installment,2.566900e+02,3.798900e+02,5.665800e+02,466285.0,1.409990e+03,4.320612e+02,15.67,2.434855e+02
int_rate,1.099000e+01,1.366000e+01,1.649000e+01,466285.0,2.606000e+01,1.382924e+01,5.42,4.357587e+00
last_pymnt_amnt,3.126200e+02,5.459600e+02,3.187510e+03,466285.0,3.623444e+04,3.123914e+03,0.00,5.554737e+03
loan_amnt,8.000000e+03,1.200000e+04,2.000000e+04,466285.0,3.500000e+04,1.431728e+04,500.00,8.286509e+03
max_bal_bc,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
member_id,4.379705e+06,1.194108e+07,2.300154e+07,466285.0,4.086083e+07,1.459766e+07,70473.00,1.168237e+07
mths_since_last_delinq,1.600000e+01,3.100000e+01,4.900000e+01,215934.0,1.880000e+02,3.410443e+01,0.00,2.177849e+01
mths_since_last_major_derog,2.600000e+01,4.200000e+01,5.900000e+01,98974.0,1.880000e+02,4.285255e+01,0.00,2.166259e+01
mths_since_last_record,5.300000e+01,7.600000e+01,1.020000e+02,62638.0,1.290000e+02,7.430601e+01,0.00,3.035765e+01
mths_since_rcnt_il,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
open_acc,8.000000e+00,1.000000e+01,1.400000e+01,466256.0,8.400000e+01,1.118707e+01,0.00,4.987526e+00
open_acc_6m,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
open_il_12m,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
open_il_24m,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
open_il_6m,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
open_rv_12m,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
open_rv_24m,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
out_prncp,0.000000e+00,4.414700e+02,7.341650e+03,466285.0,3.216038e+04,4.410062e+03,0.00,6.355079e+03
out_prncp_inv,0.000000e+00,4.413800e+02,7.338390e+03,466285.0,3.216038e+04,4.408452e+03,0.00,6.353198e+03
policy_code,1.000000e+00,1.000000e+00,1.000000e+00,466285.0,1.000000e+00,1.000000e+00,1.00,0.000000e+00
pub_rec,0.000000e+00,0.000000e+00,0.000000e+00,466256.0,6.300000e+01,1.605642e-01,0.00,5.108626e-01
recoveries,0.000000e+00,0.000000e+00,0.000000e+00,466285.0,3.352027e+04,8.534421e+01,0.00,5.522161e+02
revol_bal,6.413000e+03,1.176400e+04,2.033300e+04,466285.0,2.568995e+06,1.623020e+04,0.00,2.067625e+04
revol_util,3.920000e+01,5.760000e+01,7.470000e+01,465945.0,8.923000e+02,5.617695e+01,0.00,2.373263e+01
tot_coll_amt,0.000000e+00,0.000000e+00,0.000000e+00,396009.0,9.152545e+06,1.919135e+02,0.00,1.463021e+04
tot_cur_bal,2.861800e+04,8.153900e+04,2.089530e+05,396009.0,8.000078e+06,1.388017e+05,0.00,1.521147e+05
total_acc,1.700000e+01,2.300000e+01,3.200000e+01,466256.0,1.560000e+02,2.506443e+01,1.00,1.160014e+01
total_bal_il,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
total_cu_tl,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
total_pymnt,5.552125e+03,9.419251e+03,1.530816e+04,466285.0,5.777758e+04,1.154069e+04,0.00,8.265627e+03
total_pymnt_inv,5.499250e+03,9.355430e+03,1.523131e+04,466285.0,5.777758e+04,1.146989e+04,0.00,8.254158e+03
total_rec_int,9.572800e+02,1.818880e+03,3.304530e+03,466285.0,2.420562e+04,2.588677e+03,0.00,2.483810e+03
total_rec_late_fee,0.000000e+00,0.000000e+00,0.000000e+00,466285.0,3.586800e+02,6.501292e-01,0.00,5.265730e+00
total_rec_prncp,3.708560e+03,6.817760e+03,1.200000e+04,466285.0,3.500003e+04,8.866015e+03,0.00,7.031688e+03
total_rev_hi_lim,1.350000e+04,2.280000e+04,3.790000e+04,396009.0,9.999999e+06,3.037909e+04,0.00,3.724713e+04
verification_status_joint,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN